dist: xenial
language: python
services:
  - docker
before_install:
  - sudo apt-get update
  - pip install --upgrade --upgrade-strategy eager twine
  - pip install --upgrade --upgrade-strategy eager setuptools wheel
  - git clone https://github.com/ivy-dl/ivy_doc_builder.git /home/travis/build/ivy-dl/ivy_doc_builder
  - cd /home/travis/build/ivy-dl/ivy_doc_builder
  - pip install -r requirements.txt
  - cd /home/travis/build/ivy-dl/ivy_gym
  - pip install -r requirements.txt
  - docker pull ivydl/ivy-gym:latest
script:
  - rm -rf .gitignore
  - cd docs
  - rsync -rav /home/travis/build/ivy-dl/ivy_doc_builder/docs/ .
  - bash make_docs.sh --root_dir "../ivy_gym" --submodules_title "Environments"
  - cp .nojekyll build/
  - cd ..
  - docker run --rm -v /home/travis/build/ivy-dl/ivy_gym:/ivy_gym ivydl/ivy-gym:latest python3 -m pytest ivy_gym_tests/
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    verbose: true
    local_dir: docs/build
    email: ivydl.team@gmail.com
    name: ivy-seed
    on:
      branch: main
  - provider: script
    script: bash deploy_pypi.sh
    on:
      tags: true